
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: podtracer-role
rules:
- apiGroups:
  - ''
  resources:
  - 'Pods'
  verbs:
  - get
  - list
