apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtracer
  namespace: podtracer
  labels:
    control-plane: podtracer
spec:
  selector:
    matchLabels:
      control-plane: podtracer      
  replicas: 1
  template:
    metadata:
      name: cnf-example-pod
      namespace: podtracer
      labels:
        control-plane: podtracer      
    spec:
      serviceAccountName: podtracer-sa
      containers:
      - command:
        - /bin/bash 
        - -c 
        - --
        args:
        - "while true; do sleep 30; done;"
        image: "quay.io/fennec-project/podtracer:0.0.1"
        imagePullPolicy: Always
        name: podtracer
        volumeMounts:
          - name: kubeconfig
            mountPath: /root/.kube/
        securityContext:
          privileged: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: podtracer-kubeconfig    