apiVersion: go-remote.fennecproject.io/v1alpha1
kind: GoRemote
metadata:
  name: podtracer-dev
  namespace: podtracer-dev
spec:
  # Add fields here
  goRemoteImage: quay.io/fennec-project/goremote:0.0.1-1
  gitRepo: https://github.com/fennec-project/podtracer.git
  containerPorts:
    - containerPort: 2222
  nodeSelector:
    cnf-telco: "true"
  VolumeMounts:
    - mountPath: /host/proc
      name: proc
    - mountPath: /var/run/crio/crio.sock
      name: crio-sock
    - name: gitrepo
      mountPath: /root/go/src/github.com/project/podtracer/
  Volumes:
    - name: proc
      hostPath:
        # Mounting the proc file system to get process namespaces
        path: /proc
        type: Directory
    - name: crio-sock
      hostPath:
        # Mounting the crio socket to inspect containers
        path: /var/run/crio/crio.sock
        type: Socket
    - name: gitrepo 
      emptyDir: {}
  serviceAccount: "podtracer-dev-sa"
  goRemoteNamespace: "podtracer-dev"