apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podtracer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podtracer-role
subjects:
- kind: ServiceAccount
  name: podtracer-sa
  namespace: podtracer-dev