apiVersion: v1
kind: Namespace
metadata:
  name: cnf-telco
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnf-telco-sa
  namespace: cnf-telco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-example-pod
  namespace: cnf-telco
  labels:
    networkMonitor: "true"
spec:
  selector:
    matchLabels:
      networkMonitor: "true"
  replicas: 10
  template:
    metadata:
      name: cnf-example-pod
      namespace: cnf-telco
      labels:
        networkMonitor: "true"
    spec:
      serviceAccountName: cnf-telco-sa
      containers:
      - command:
        - /bin/ping
        args:
          - 8.8.8.8
        image: "nicolaka/netshoot:latest"
        imagePullPolicy: Always
        name: cnf-example
      # - command:
      #   - /bin/bash 
      #   - -c 
      #   - --
      #   args:
      #   - "while true; do sleep 30; done;"        
      # nodeSelector:
      #   cnf-telco: "true"        
